/**
 * Transform Definitions — static metadata for all available transforms.
 * Each transform wraps one or more existing collectors.
 */

import type { TransformDefinition } from '@nexusgraph/shared';

export const TRANSFORM_DEFINITIONS: TransformDefinition[] = [
  // ─── Web Transforms ─────────────────────────────────────────────────
  {
    id: 'web.discover-official-site',
    name: 'Discover Official Website',
    description: 'Search for official website associated with an organization or name using public web search',
    inputTypes: ['ORGANIZATION', 'PERSON'],
    outputTypes: ['WEBSITE', 'URL', 'DOMAIN'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },

  // ─── Domain/Infrastructure Transforms ───────────────────────────────
  {
    id: 'domain.resolve-dns',
    name: 'DNS Resolution',
    description: 'Resolve A, AAAA, MX, NS, TXT, CNAME records for a domain',
    inputTypes: ['DOMAIN', 'WEBSITE', 'SUBDOMAIN'],
    outputTypes: ['IP_ADDRESS', 'MX_RECORD', 'NS_RECORD', 'SUBDOMAIN'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.find-subdomains-crt',
    name: 'Subdomain Enumeration (crt.name)',
    description: 'Enumerate subdomains of an apex domain from public Certificate Transparency logs via crt.name',
    inputTypes: ['DOMAIN', 'WEBSITE', 'URL', 'ORGANIZATION'],
    outputTypes: ['SUBDOMAIN', 'DOMAIN'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.find-tls',
    name: 'TLS Certificate Lookup',
    description: 'Find TLS certificates and Subject Alternative Names via Certificate Transparency logs',
    inputTypes: ['DOMAIN', 'SUBDOMAIN'],
    outputTypes: ['CERTIFICATE', 'SUBDOMAIN', 'DOMAIN'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.webpage-metadata',
    name: 'Webpage Metadata Extraction',
    description: 'Extract page title, headers, social links, contact info, and technology stack from a URL',
    inputTypes: ['URL', 'WEBSITE', 'DOMAIN'],
    outputTypes: ['EMAIL', 'SOCIAL_PROFILE', 'TECHNOLOGY', 'PHONE'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.xnlinkfinder-js-params',
    name: 'Frontend JS & Parameter Recon (xnLinkFinder)',
    description: 'Crawl target to uncover hidden REST endpoints, query parameters, JS variables, and secrets embedded in frontend JavaScript bundles',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['URL', 'DOCUMENT', 'SUBDOMAIN'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.historical-urls',
    name: 'Historical Endpoints (Wayback CDX)',
    description: 'Query public Internet Archive Wayback Machine CDX API to discover archived endpoints, hidden query parameters, and past site structure',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['URL', 'SUBDOMAIN'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.web-exposure',
    name: 'Web Exposure & Security Policy',
    description: 'Probe security.txt (RFC 9116), sitemap.xml, and crawler policies to uncover vulnerability disclosure contacts, portal routes, and administrative entry points',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['EMAIL', 'URL', 'DOCUMENT'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.reverse-ip',
    name: 'Reverse IP & Virtual Host Neighbors',
    description: 'Identify sibling domains and co-hosted websites sharing the same server or infrastructure via public reverse IP registries',
    inputTypes: ['DOMAIN', 'IP_ADDRESS', 'URL', 'WEBSITE'],
    outputTypes: ['DOMAIN', 'IP_ADDRESS'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.favicon-hash',
    name: 'Favicon MurmurHash3 & Origin Discovery',
    description: 'Fingerprint target website favicon using MurmurHash3 and generate Shodan/Censys search pivots to uncover the origin server IP behind WAF/CDN',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['TECHNOLOGY'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.whois-rdap',
    name: 'WHOIS / RDAP Registration Lookup',
    description: 'Query authoritative RFC 7483 RDAP records for domain registrar, creation/expiration dates, nameservers, and registrant details',
    inputTypes: ['DOMAIN', 'WEBSITE', 'URL'],
    outputTypes: ['ORGANIZATION', 'NS_RECORD', 'PERSON'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'infrastructure.ip-geolocation',
    name: 'IP Geolocation & ASN Lookup',
    description: 'Geolocate an IP address to resolve city, country, coordinates, ISP, and Autonomous System (ASN)',
    inputTypes: ['IP_ADDRESS'],
    outputTypes: ['LOCATION', 'ORGANIZATION'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },

  // ─── Social Transforms ──────────────────────────────────────────────
  {
    id: 'social.rapidapi-social-lookup',
    name: 'RapidAPI Social Deep Recon',
    description: 'Deep reconnaissance across Instagram, TikTok, and LinkedIn to extract full names, emails, phones, workplaces, and locations',
    inputTypes: ['USERNAME', 'SOCIAL_PROFILE', 'PERSON'],
    outputTypes: ['SOCIAL_PROFILE', 'PERSON', 'EMAIL', 'PHONE', 'ORGANIZATION', 'LOCATION', 'WEBSITE'],
    category: 'social',
    riskLevel: 'low',
    enabled: true,
    requiresApiKey: true,
    apiKeyName: 'RAPIDAPI_KEY',
  },
  {
    id: 'social.discover-public-profiles',
    name: 'Public Social Profile Discovery',
    description: 'Check for public profile existence across major platforms',
    inputTypes: ['USERNAME'],
    outputTypes: ['SOCIAL_PROFILE', 'USERNAME'],
    category: 'social',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'social.youtube-channel',
    name: 'YouTube Channel Discovery',
    description: 'Find public YouTube channels matching organization or username',
    inputTypes: ['USERNAME', 'ORGANIZATION'],
    outputTypes: ['YOUTUBE_CHANNEL', 'URL'],
    category: 'social',
    riskLevel: 'low',
    enabled: true,
  },

  // ─── Developer Platform Transforms ──────────────────────────────────
  {
    id: 'developer.github-profile',
    name: 'GitHub Profile Discovery',
    description: 'Find public GitHub user/organization profiles, repositories, and associated metadata',
    inputTypes: ['USERNAME', 'ORGANIZATION', 'EMAIL'],
    outputTypes: ['GITHUB_PROFILE', 'REPOSITORY', 'EMAIL', 'URL', 'ORGANIZATION'],
    category: 'developer',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'developer.gitlab-profile',
    name: 'GitLab Profile Discovery',
    description: 'Find public GitLab user profiles and repositories',
    inputTypes: ['USERNAME', 'ORGANIZATION'],
    outputTypes: ['GITLAB_PROFILE', 'REPOSITORY', 'URL'],
    category: 'developer',
    riskLevel: 'low',
    enabled: true,
  },

  // ─── Contact Transforms ─────────────────────────────────────────────
  {
    id: 'phone.geo-metadata',
    name: 'Phone Number Geolocation',
    description: 'Parse an international phone number (E.164) and attribute its registered country region as coordinates',
    inputTypes: ['PHONE'],
    outputTypes: ['PHONE', 'LOCATION'],
    category: 'contact',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'contact.find-official-contact',
    name: 'Official Contact Information',
    description: 'Extract official public contact details (email, phone) from organization websites',
    inputTypes: ['WEBSITE', 'URL', 'DOMAIN'],
    outputTypes: ['EMAIL', 'PHONE', 'ADDRESS', 'LOCATION'],
    category: 'contact',
    riskLevel: 'low',
    enabled: true,
  },

  {
    id: 'social.username-sweep',
    name: 'Mr.Holmes Username Sweep',
    description: 'Sweep a username across 150+ platforms ported from Mr.Holmes (status, message and redirect based detection)',
    inputTypes: ['USERNAME'],
    outputTypes: ['SOCIAL_PROFILE', 'URL'],
    category: 'social',
    riskLevel: 'medium',
    enabled: true,
  },
  {
    id: 'intelligence.generate-dorks',
    name: 'Mr.Holmes Website Dork Generator',
    description: 'Generate deterministic Google/Yandex site-scoped dork URLs (filetype, intext, inurl) for domain and website investigations',
    inputTypes: ['DOMAIN', 'URL'],
    outputTypes: ['URL', 'PUBLIC_MENTION'],
    category: 'intelligence',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'contact.holehe-email-crawl',
    name: 'Holehe Email Account Crawler',
    description: 'Crawl 120+ web platforms, social networks, and online services to discover registered accounts for an email address',
    inputTypes: ['EMAIL'],
    outputTypes: ['SOCIAL_PROFILE', 'URL', 'GITHUB_PROFILE', 'PHONE', 'EMAIL'],
    category: 'contact',
    riskLevel: 'medium',
    enabled: true,
  },
  {
    id: 'contact.email-breach-lookup',
    name: 'Mr.Holmes Email Lookup',
    description: 'Find GitHub accounts listing the email publicly, check Gravatar existence, and persist breach-lookup reference links',
    inputTypes: ['EMAIL'],
    outputTypes: ['GITHUB_PROFILE', 'SOCIAL_PROFILE', 'URL'],
    category: 'contact',
    riskLevel: 'medium',
    enabled: true,
  },
  {
    id: 'domain.website-recon',
    name: 'Mr.Holmes Website Recon',
    description: 'Fetch robots.txt rules, resolve hosting IP with geolocation, and persist reputation-check reference links',
    inputTypes: ['DOMAIN', 'WEBSITE', 'URL'],
    outputTypes: ['DOCUMENT', 'LOCATION', 'IP_ADDRESS', 'URL'],
    category: 'infrastructure',
    riskLevel: 'medium',
    enabled: true,
  },

  {
    id: 'social.mrholmes-engine',
    name: 'Mr.Holmes Python Engine',
    description: 'Run the original vendored Mr.Holmes Python engine — SOCIAL-ACCOUNT-OSINT for usernames and PEOPLE-OSINT for names (150+ platforms)',
    inputTypes: ['USERNAME', 'PERSON'],
    outputTypes: ['SOCIAL_PROFILE', 'URL'],
    category: 'social',
    riskLevel: 'medium',
    enabled: true,
  },
  {
    id: 'contact.mrholmes-phone',
    name: 'Mr.Holmes Phone OSINT',
    description: 'Run the original Mr.Holmes PHONE-NUMBER-OSINT category: carrier, approximate geolocation coordinates (Nominatim OSM), timezones, and dorks',
    inputTypes: ['PHONE'],
    outputTypes: ['LOCATION', 'URL'],
    category: 'contact',
    riskLevel: 'low',
    enabled: true,
  },

  {
    id: 'infrastructure.shodan-recon',
    name: 'Shodan Port & Host Intelligence',
    description: 'Enumerate open ports, running network services, banners, CPE, technologies, and vulnerabilities indexed by Shodan',
    inputTypes: ['IP_ADDRESS', 'DOMAIN', 'URL'],
    outputTypes: ['IP_ADDRESS', 'TECHNOLOGY', 'LOCATION', 'ORGANIZATION', 'DOMAIN'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.subdomain-takeover',
    name: 'Subdomain Takeover & Dangling DNS Validator',
    description: 'Audit CNAME records against 18+ cloud hosting signatures (AWS S3, GitHub Pages, Heroku, Azure, Zendesk, Shopify) and detect dangling takeover risks',
    inputTypes: ['DOMAIN', 'URL', 'SUBDOMAIN'],
    outputTypes: ['SUBDOMAIN', 'DOCUMENT'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.dns-security-audit',
    name: 'Deep DNS Security & Email Spoofing Audit',
    description: 'Audit SPF mechanisms (-all vs ~all), DMARC policy enforcement, DKIM probing, CAA issuance restrictions, and verified SaaS vendor tokens',
    inputTypes: ['DOMAIN', 'URL', 'EMAIL'],
    outputTypes: ['ORGANIZATION', 'DOCUMENT', 'EMAIL'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.sensitive-url-classifier',
    name: 'Sensitive Query Parameter & Route Classifier',
    description: 'Classify discovered endpoints into high-risk security categories: Auth Tokens, SSRF/Open Redirects, File Inclusion, IDOR, and Debug/Admin routes',
    inputTypes: ['DOMAIN', 'URL'],
    outputTypes: ['URL', 'DOCUMENT'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.web-tech-fingerprint',
    name: 'Web Technology Stack Fingerprinter',
    description: 'Identify web servers, backend frameworks, CMS platforms, CDN/WAF layers, analytics trackers, and frontend libraries from HTTP headers and DOM signatures',
    inputTypes: ['DOMAIN', 'URL'],
    outputTypes: ['TECHNOLOGY'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },

  {
    id: 'domain.tracking-ids',
    name: 'Tracking ID & Analytics Pivoting',
    description: 'Extract Google Analytics (GA4/UA), GTM, AdSense, Meta Pixel, and marketing tags for OSINT identity and infrastructure pivoting',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['TECHNOLOGY'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.site-crawler',
    name: 'Deep Site Architecture & Security Crawler',
    description: 'Deep crawl robots.txt disallowed sensitive paths, sitemap.xml architecture, and RFC 9116 security.txt disclosure contacts',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['URL', 'DOCUMENT', 'EMAIL'],
    category: 'web',
    riskLevel: 'low',
    enabled: true,
  },
  {
    id: 'domain.http-security-audit',
    name: 'HTTP Security Headers & WAF Health Audit',
    description: 'Inspect live response headers for WAF/CDN perimeter protection (Cloudflare, CloudFront, Akamai) and evaluate security headers compliance (HSTS, CSP, CORS)',
    inputTypes: ['DOMAIN', 'URL', 'WEBSITE'],
    outputTypes: ['TECHNOLOGY'],
    category: 'infrastructure',
    riskLevel: 'low',
    enabled: true,
  },

  // ─── Intelligence Transforms ────────────────────────────────────────
  {
    id: 'mentions.search-public-web',
    name: 'Public Web Mentions',
    description: 'Search for public mentions and references across the web',
    inputTypes: ['DOMAIN', 'IP_ADDRESS', 'URL', 'ORGANIZATION'],
    outputTypes: ['PUBLIC_MENTION', 'URL', 'WEBSITE'],
    category: 'intelligence',
    riskLevel: 'low',
    enabled: true,
  },
];
